name: 下载、扫描并上传

on:
  workflow_dispatch:
    inputs:
      domain:
        description: '要扫描的域名'
        required: true
        type: string

jobs:
  download_and_scan:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1: 检出代码
      - name: 检出代码
        uses: actions/checkout@v3

      # 步骤 2: 下载 test.zip 文件
      - name: 下载 test.zip
        run: |
          curl -L -o test.zip "https://fs-im-kefu.7moor-fs1.com/ly/4d2c3f00-7d4c-11e5-af15-41bf63ae4ea0/1730886995302/test.zip"

      # 步骤 3: 解压下载的文件
      - name: 解压下载的文件
        run: |
          unzip -q test.zip -d ./test_files
          rm test.zip  # 解压后删除 test.zip 文件

      # 步骤 4: 进入解压目录并运行 xscan
      - name: 进入解压目录并运行 xscan
        run: |
          cd ./test_files
          chmod +x xscan
          ./xscan spider --url ${{ github.event.inputs.domain }}

      # 步骤 5: 重命名文件夹为当前时间并保存路径变量
      - name: 重命名文件夹为当前时间
        run: |
          current_time=$(date +"%Y%m%d_%H%M%S")
          mv ./test_files ./test_files_$current_time
          echo "folder_name=test_files_$current_time" >> $GITHUB_ENV

      # 步骤 6: 删除不需要的文件
      - name: 删除 config.yaml, dict, readme.md, xscan
        run: |
          rm -f ./${{ env.folder_name }}/config.yaml ./${{ env.folder_name }}/dict ./${{ env.folder_name }}/readme.md ./${{ env.folder_name }}/xscan

      # 步骤 7: 将生成的文件提交回存储库
      - name: Commit results to Github
        run: |
          git config --local user.email "2991885177@qq.com"
          git config --global user.name "joejoequte"
          cd ./${{ env.folder_name }}
          git add .
          git commit -m "上传扫描结果"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/joejoequte/xtest.git
