name: 下载、扫描并上传

on:
  workflow_dispatch:  # 允许手动触发
    inputs:
      domain:
        description: '要扫描的域名'
        required: true
        type: string

jobs:
  download_and_scan:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1: 检出代码
      - name: 检出代码
        uses: actions/checkout@v3  # 自动获取最新版本

      # 步骤 2: 下载 test.zip 文件
      - name: 下载 test.zip
        run: |
          curl -L -o test.zip "https://fs-im-kefu.7moor-fs1.com/ly/4d2c3f00-7d4c-11e5-af15-41bf63ae4ea0/1730886995302/test.zip"

      # 步骤 3: 解压下载的文件
      - name: 解压下载的文件
        run: |
          unzip test.zip -d ./test_files
          rm test.zip  # 解压后删除 test.zip 文件

      # 步骤 4: 进入解压目录并运行 xscan
      - name: 进入解压目录并运行 xscan
        run: |
          cd ./test_files
          chmod +x xscan  # 给 xscan 添加可执行权限 
          ./xscan spider --url ${{ github.event.inputs.domain }}

      # 步骤 5: 将生成的文件提交回存储库
      - name: 提交扫描结果到 GitHub 存储库
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cd ./test_files
          git add .
          git commit -m "上传扫描结果"
          git push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
